import { config } from '../config.js';
import { escapeHtml } from '../utils/text.js';

const baseCss = `*{box-sizing:border-box}body{margin:0;font-family:Inter,system-ui,Arial;background:#0b1220;color:#e5e7eb}.wrap{max-width:980px;margin:0 auto;padding:32px 20px}.card{background:#111b2e;border:1px solid #26334d;border-radius:18px;padding:24px;box-shadow:0 18px 60px #0005}.grid{display:grid;grid-template-columns:360px 1fr;gap:20px}.muted{color:#94a3b8}.status{display:inline-block;padding:7px 12px;border-radius:999px;background:#24324a;font-weight:700}.qr{width:100%;max-width:340px;aspect-ratio:1;background:#fff;border-radius:12px;padding:10px;object-fit:contain}.actions{display:flex;gap:10px;flex-wrap:wrap;margin-top:18px}button,input{font:inherit}button{border:0;border-radius:10px;padding:11px 16px;cursor:pointer;font-weight:700;background:#22c55e;color:#052e16}button.danger{background:#ef4444;color:#fff}button.secondary{background:#334155;color:#fff}pre{white-space:pre-wrap;word-break:break-word;background:#0a1020;padding:14px;border-radius:12px;max-height:430px;overflow:auto;font-size:12px}.login{max-width:420px;margin:10vh auto}.field{display:flex;flex-direction:column;gap:7px;margin:14px 0}input{padding:12px;border-radius:10px;border:1px solid #334155;background:#0b1220;color:#fff}.error{background:#7f1d1d;padding:10px;border-radius:10px}@media(max-width:760px){.grid{grid-template-columns:1fr}}`;
const layout = (body, script='') => `<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escapeHtml(config.botName)} Admin</title><style>${baseCss}</style></head><body>${body}${script}</body></html>`;

export const renderLogin = (error) => layout(`<main class="wrap"><section class="card login"><h1>🔐 Painel administrativo</h1><p class="muted">Entre para conectar e administrar o WhatsApp.</p>${error ? '<p class="error">Usuário ou senha inválidos.</p>' : ''}<form method="post" action="/admin/login"><label class="field">Usuário<input name="username" autocomplete="username" required></label><label class="field">Senha<input name="password" type="password" autocomplete="current-password" required></label><button type="submit">Entrar</button></form></section></main>`);

export const renderAdmin = () => layout(`<main class="wrap"><div style="display:flex;justify-content:space-between;align-items:center;gap:15px"><div><h1>🛍️ ${escapeHtml(config.botName)}</h1><p class="muted">Conexão do WhatsApp e registros do bot.</p></div><form method="post" action="/admin/logout"><button class="secondary">Sair</button></form></div><section class="grid"><div class="card"><h2>WhatsApp</h2><p>Status: <span id="status" class="status">carregando</span></p><div id="qrBox"><p class="muted">Aguardando QR Code...</p></div><p id="user" class="muted"></p><p id="error" class="error" style="display:none"></p><div class="actions"><button onclick="action('/admin/api/restart')">Reiniciar</button><button class="danger" onclick="disconnect()">Desconectar sessão</button></div></div><div class="card"><h2>Logs recentes</h2><pre id="logs">Carregando...</pre></div></section></main>`, `<script>
const statusLabels={connected:'Conectado',connecting:'Conectando',starting:'Iniciando',qr:'Aguardando leitura do QR',disconnected:'Desconectado',logged_out:'Sessão encerrada',error:'Erro',restarting:'Reiniciando'};
async function refresh(){try{const r=await fetch('/admin/api/status',{cache:'no-store'});if(!r.ok)return location.href='/admin/login';const d=await r.json();document.querySelector('#status').textContent=statusLabels[d.status]||d.status;document.querySelector('#qrBox').innerHTML=d.qrDataUrl?'<img class="qr" alt="QR Code do WhatsApp" src="'+d.qrDataUrl+'"><p class="muted">WhatsApp → Aparelhos conectados → Conectar aparelho.</p>':'<p class="muted">'+(d.status==='connected'?'WhatsApp conectado.':'Aguardando geração do QR Code...')+'</p>';document.querySelector('#user').textContent=d.user?.id?'Conta: '+d.user.id:'';const e=document.querySelector('#error');e.style.display=d.lastError?'block':'none';e.textContent=d.lastError||'';document.querySelector('#logs').textContent=(d.logs||[]).map(x=>new Date(x.created_at).toLocaleString('pt-BR')+' ['+x.level+'] '+x.event+' '+JSON.stringify(x.details)).join('\n')||'Nenhum log.';}catch(e){console.error(e)}}
async function action(url){await fetch(url,{method:'POST'});setTimeout(refresh,800)}
async function disconnect(){if(confirm('Encerrar a sessão atual e gerar um novo QR Code?'))await action('/admin/api/disconnect')}
refresh();setInterval(refresh,3000);
</script>`);
